### ISSUE TITLE
[BUG] Preview screen astrolabe is sometimes incorrect

### ISSUE THREAD

**Issue by thearst3rd** [MBU-Team/OpenMBU#104]
[//]: # (Describe what's going wrong:)
### What's going wrong

_Sometimes_, when starting OpenMBU, the preview screen for the advanced levels will have the beginner astrolabe texture (or just one that's much brighter than intended). Here is a screenshot with the incorrect astrolabe:

![OpenMBU-WrongAstrolabe](https://user-images.githubusercontent.com/7307599/129291871-4a678d10-3cb0-4f12-9766-f21cb33d8c5d.png)

[//]: # (Describe what should happen:)
### What should happen

The astrolabe for the advanced levels is much darker and should look like this (screenshot taken after restarting the game):

![OpenMBU-CorrectAstrolabe](https://user-images.githubusercontent.com/7307599/129291889-998832f6-ba28-4394-bdce-2c2e39a863a2.png)

Looking at them side by side, they look like they could maybe be just different colorations of the same texture? I'm not sure how it works under the hood.

I wish I could give a better explanation then "it sometimes happens, and it sometimes doesn't", but so far I haven't been able to pinpoint a 100% reproducible way to make it happen. I'm assuming that it's just a binary thing, like it's either too bright or it isn't, but I'm wondering if varying levels of discoloration can happen. ¯\\\_(ツ)\_/¯

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by HumanGamer** [comment]
I'll look into this soon.
