### ISSUE TITLE
[BUG] Physics bug out when there is high latency

### ISSUE THREAD

**Issue by HumanGamer** [MBU-Team/OpenMBU#107]
When there is high latency (tested between North America and Europe), the physics can become really glitchy when the 2 marbles are in close proximity.

**Comment by neolightning** [comment]
This also applies to matches hosted on the same machine. Sometimes this will cause a crash
![Multiplayer Physics Crash Local](https://user-images.githubusercontent.com/6211989/144532136-da706796-a647-4e29-9515-415ec00286fb.png)

**Comment by neolightning** [comment]
Tested with following builds

Release build causes it to glitch out and crash

Optimized Debug has no issues related to this

Debug has no issues related to this

**Comment by thearst3rd** [comment]
Since we've switched to using OPTIMIZEDDEBUG (which it seems is what the original MBO did :eyes:), is this bug still a thing? If not, we should close it.

Or, we could repurpose this ticket to be fixing the bug in _release_ mode specifically.
