### ISSUE TITLE
[BUG] Time Travel Glass Render Broken

### ISSUE THREAD

**Issue by neolightning** [MBU-Team/OpenMBU#110]
The glass is showing the sky objects and nothing else when looking through the time travel
![TT Broken Glass](https://user-images.githubusercontent.com/6211989/144528696-2664aed6-3f67-45cc-bb94-af38c92b5880.png)

**Comment by HumanGamer** [comment]
This was caused by fixing the glass transparency, but that fix caused too many issues and has been reverted for now. So this bug is no longer a thing.
