### ISSUE TITLE
[REQUEST] How "portable" is this codebase?

### ISSUE THREAD

**Issue by Techguy791** [MBU-Team/OpenMBU#122]
I'm wondering if this codebase has too many dependencies to be ported to other platforms, such as Android, Linux, or even game consoles such as the PS Vita.

**Comment by thearst3rd** [comment]
Unfortunately at the moment, the code is pretty Windows-specific, relying on DirectX for rendering and not compiling correctly under GCC. However, making the code more cross platform and portable is a priority - we're attempting to update the rendering system to allow us to use OpenGL (and maybe others?) and working on compiling with GCC. So, unfortunately it's not there yet but we're working on it!

**Comment by Techguy791** [comment]
> Unfortunately at the moment, the code is pretty Windows-specific, relying on DirectX for rendering and not compiling correctly under GCC. However, making the code more cross platform and portable is a priority - we're attempting to update the rendering system to allow us to use OpenGL (and maybe others?) and working on compiling with GCC. So, unfortunately it's not there yet but we're working on it!

Thanks for the insight! One more question, how does this relate to the 2015(?) port of MBU at https://old.marblevortex.com ? I couldn't find any documentation on how it was made, so I have no idea if it's a decompilation that was never open-sourced, or an insane mod of MBG or MBP.

**Comment by neolightning** [comment]
> > Unfortunately at the moment, the code is pretty Windows-specific, relying on DirectX for rendering and not compiling correctly under GCC. However, making the code more cross platform and portable is a priority - we're attempting to update the rendering system to allow us to use OpenGL (and maybe others?) and working on compiling with GCC. So, unfortunately it's not there yet but we're working on it!
> 
> Thanks for the insight! One more question, how does this relate to the 2015(?) port of MBU at https://old.marblevortex.com ? I couldn't find any documentation on how it was made, so I have no idea if it's a decompilation that was never open-sourced, or an insane mod of MBG or MBP.

The 2015 port of MBU is actually Marble Blast Online, which was a version made by Garage Games to run in a web browser for InstantAction.com, We took that and pretty much did so many weird hacks just to make it work right as a normal game, we even tried to re-add lost features from the Xbox 360 build such as the Level Previews, but because no one has the source anymore, there was not much that can be done. There was other issues too like the editor dropdowns acting like buttons which would crash the game.

**Comment by Techguy791** [comment]
> > > Unfortunately at the moment, the code is pretty Windows-specific, relying on DirectX for rendering and not compiling correctly under GCC. However, making the code more cross platform and portable is a priority - we're attempting to update the rendering system to allow us to use OpenGL (and maybe others?) and working on compiling with GCC. So, unfortunately it's not there yet but we're working on it!
> > 
> > Thanks for the insight! One more question, how does this relate to the 2015(?) port of MBU at https://old.marblevortex.com ? I couldn't find any documentation on how it was made, so I have no idea if it's a decompilation that was never open-sourced, or an insane mod of MBG or MBP.
> 
> The 2015 port of MBU is actually Marble Blast Online, which was a version made by Garage Games to run in a web browser for InstantAction.com, We took that and pretty much did so many weird hacks just to make it work right as a normal game, we even tried to re-add lost features from the Xbox 360 build such as the Level Previews, but because no one has the source anymore, there was not much that can be done. There was other issues too like the editor dropdowns acting like buttons which would crash the game.

That makes sense. Are there any plans to re-add the custom levels from that version (or allow people to swap them in themselves?)

**Comment by neolightning** [comment]
> > > > Unfortunately at the moment, the code is pretty Windows-specific, relying on DirectX for rendering and not compiling correctly under GCC. However, making the code more cross platform and portable is a priority - we're attempting to update the rendering system to allow us to use OpenGL (and maybe others?) and working on compiling with GCC. So, unfortunately it's not there yet but we're working on it!
> > > 
> > > 
> > > Thanks for the insight! One more question, how does this relate to the 2015(?) port of MBU at https://old.marblevortex.com ? I couldn't find any documentation on how it was made, so I have no idea if it's a decompilation that was never open-sourced, or an insane mod of MBG or MBP.
> > 
> > 
> > The 2015 port of MBU is actually Marble Blast Online, which was a version made by Garage Games to run in a web browser for InstantAction.com, We took that and pretty much did so many weird hacks just to make it work right as a normal game, we even tried to re-add lost features from the Xbox 360 build such as the Level Previews, but because no one has the source anymore, there was not much that can be done. There was other issues too like the editor dropdowns acting like buttons which would crash the game.
> 
> That makes sense. Are there any plans to re-add the custom levels from that version (or allow people to swap them in themselves?)

There is plans after 1.0 for OpenMBU to allow custom content with tools such as a online content browser and even eventually a built in mesh making tool

**Comment by Techguy791** [comment]
That sounds great! I can't wait to see where this project goes in the future!
