### ISSUE TITLE
[BUG] Setting audio volumes to zero can cause performance issues

### ISSUE THREAD

**Issue by thearst3rd** [MBU-Team/OpenMBU#123]
After setting both sound and music volume to zero and restarting the game, the performance will drastically lower when entering a level. Setting either sound or music volumes after the fact will fix the issues. Also, changing the audio down to zero after the game has already started doesn't cause issues.

Sometimes, when the game is in the zero-audio laggy state, finishing a level will crash the game (especially if the marble contacts the finish pad during the animation). I don't know if it's related, or if it just always happens when the framerate is this low.

Video of the bug: https://youtu.be/3w2MT5wSYhY

Gonna be honest, this one boggles me. I think there might be some optimization where the audio system doesn't initialize if all audio is set to zero when the game boots, and that's somehow causing an issue somewhere.

Log of the game after the finish pad crash:
[console.log](https://github.com/MBU-Team/OpenMBU/files/8065908/console.log)

**Comment by HumanGamer** [comment]
Wait what?! How does this even happen lmao

**Comment by HumanGamer** [comment]
This should be fixed as of 3ffa5f1f3a393f32bf6cb13472557564fb4abb30 and a8689bb6ac110894521104f8b327d5a9416907ed
