### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Techguy791** [MBU-Team/OpenMBU#124]
There haven't been any commits to the repository in months, and the official Discord server hasn't seen any activity in a long time. Is this project cancelled?

**Comment by MrTwatWaffle** [comment]
no lol, the discord is dead because most of us that are "active" chat in dms and its not canceled it just takes a while to work on and actually do things

**Comment by Techguy791** [comment]
Woah, I wasn't trying to be annoying. I know stuff takes time. I was curious because there hasn't been so much as a whisper of activity on anything public recently. Typically repos that haven't been touched in several months are considered dead.

**Comment by MrTwatWaffle** [comment]
oh you didn't come off as annoying, and it really donest get much commits because its really just a fan project and only a few of us actually working on it

**Comment by AntAptive** [comment]
> There haven't been any commits to the repository in months, and the official Discord server hasn't seen any activity in a long time. Is this project cancelled?

Hi @Techguy791. No, the project is still very much alive! We are still actively working on it! 😄

**Comment by Techguy791** [comment]
Gotcha then. Thanks!
