### ISSUE TITLE
[BUG] Respawning on an angled checkpoint tilts entire level to be flat with the checkpoint

### ISSUE THREAD

**Issue by linguini15** [MBU-Team/OpenMBU#130]
https://youtu.be/25HDtBijg6I

If you respawn on an angled checkpoint the level tilts so the checkpoint is flat. might be the code for gravity directions misbehaving. best solution for this would probably be to have a gravity direction override for checkpoints.

how to reproduce
1. go to level Will o' Wisp
2. hit checkpoint shown at 0:33 in video
3. die/hit respawn button

**Comment by thearst3rd** [comment]
This actually isn't a bug with OpenMBU, that's how the level really behaves on the original Xbox 360 release:

https://www.youtube.com/watch?v=hrrqhjL_EHk

For custom levels (after 1.0 release), having that extra gravity direction option will probably be a good idea.
