### ISSUE TITLE
[BUG] Sound Broken On Multiplayer

### ISSUE THREAD

**Issue by neolightning** [MBU-Team/OpenMBU#131]
Sounds are still pitching wrong when playing multiplayer.

**Comment by HumanGamer** [comment]
We've determined this is an issue with DirectSound, and we plan to replace it with XAudio.

**Comment by HumanGamer** [comment]
XAudio support was added in 3ffa5f1f3a393f32bf6cb13472557564fb4abb30 and DirectSound was removed in a8689bb6ac110894521104f8b327d5a9416907ed.

This should now be fixed.
