### ISSUE TITLE
[BUG] Marble lighting is off

### ISSUE THREAD

**Issue by thearst3rd** [MBU-Team/OpenMBU#137]
More confirmation needs to be done to check these against the real xbox 360 version.

The dark side of the marble seems a bit too dark:

![image](https://user-images.githubusercontent.com/7307599/192408898-446e29d9-b884-4f45-b0ed-3e994ec2257a.png)

Mega marble lighting is very extreme:

![image](https://user-images.githubusercontent.com/7307599/192408951-cffc920e-9629-40ec-b6b5-b616c5d6ea58.png)
![image](https://user-images.githubusercontent.com/7307599/192408960-4a02e47a-0510-4bba-b75f-616d4cf80ace.png)

**What it should look like:** (Screenshots from Xenia)

![image](https://user-images.githubusercontent.com/7307599/192409072-c96c4237-5651-4e37-ada0-af74da589495.png)
![image](https://user-images.githubusercontent.com/7307599/192409100-ac6b3de1-52f0-4d6a-a5ea-38c7f270a1eb.png)
![image](https://user-images.githubusercontent.com/7307599/192409126-7c106e1e-f637-4120-9c2e-ab172dd7ee5e.png)

May be related to #35

**Comment by neolightning** [comment]
I know I have complained about this before.

**Comment by HumanGamer** [comment]
Fixed in b64f4d79412060cfbb7fb31a3b63bafb30487bec
