### ISSUE TITLE
[BUG] Coloring of blue start pad bits are off

### ISSUE THREAD

**Issue by thearst3rd** [MBU-Team/OpenMBU#138]
The coloring on the small blue bits which animate on the start pad seem washed out:

![image](https://user-images.githubusercontent.com/7307599/192409498-fc27ae04-96f4-42ae-a24c-ff2673edbed1.png)
![image](https://user-images.githubusercontent.com/7307599/192409508-769a1a7a-58a2-4328-8097-06ae87bf45a6.png)
![image](https://user-images.githubusercontent.com/7307599/192409520-23ceb38e-66d4-479d-99d6-ec89ff775bf8.png)

**What is should look like:** (Screenshots from Xenia)

![image](https://user-images.githubusercontent.com/7307599/192409594-c83fa964-41cd-466b-9512-7fde0e7eb925.png)
![image](https://user-images.githubusercontent.com/7307599/192409637-24472aa6-391b-4b4e-a923-50317d6cdbce.png)
![image](https://user-images.githubusercontent.com/7307599/192409657-e481228f-1ae4-4cef-b21f-38865feecb5a.png)

May be related to #35

**Comment by HumanGamer** [comment]
Some work on this was done in b64f4d79412060cfbb7fb31a3b63bafb30487bec but it's still not 100% accurate.

**Comment by HumanGamer** [comment]
Fixed in 1d71e7abaa6445cf21ff8da2bcb48bda0e0707bc
