### ISSUE TITLE
[BUG] OpenMBU's glow is too intense and doesn't fade in on checkpoints.

### ISSUE THREAD

**Issue by HumanGamer** [MBU-Team/OpenMBU#142]
In OpenMBU the glow is way too intense and also does not fade in when getting a checkpoint.

Here is a comparison video:

https://user-images.githubusercontent.com/39096122/213036928-041f1299-5c06-4d54-99bd-028116fcce88.mp4

**Comment by HumanGamer** [comment]
Mostly fixed in d791110ad2654aef9b21f3f6ad1896dc8f82c831, however it can still have issues fading in on some checkpoints. We need to look into this.

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/MBU-Team/OpenMBU/commit/bb0cd28116a1f4b4da0e41e42fd3fc67602c68b1
