### ISSUE TITLE
[BUG] Game crashes on newer versions past version 1.12. 1.12 works without crashing btw.

### ISSUE THREAD

**Issue by Jackthechief1** [MBU-Team/OpenMBU#150]
This is Serpent#8138 on discord
[//]: # (Describe what's going wrong:)
Game crashes on newer versions past 1.12
I used the console to see the game's stuff, guided by the discord owner and saw that "Missing SpawnPoint SimGroup" exists in the console when the game crashes.
[//]: # (Describe what should happen:)
The game should be able to play without crashing on startup on the newer versions past 1.12

My specs are: 
Processor	AMD Ryzen 7 5825U with Radeon Graphics            2.00 GHz
Installed RAM	16.0 GB (15.4 GB usable)
Device ID	758F5604-5070-45C7-A99C-9906024131B1
Product ID	00342-22031-25217-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
Edition	Windows 11 Home
Version	22H2
Installed on    ‎9/‎21/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by AJ-Ferguson** [comment]
This was solved in Discord. [Link to post](https://discord.com/channels/265605947144142848/1079936936334069811)
The solution was to install the DirectX runtime.
