### ISSUE TITLE
[BUG] Switching to Borderless Window borks the game for the first time

### ISSUE THREAD

**Issue by HumanGamer** [MBU-Team/OpenMBU#170]
When you don't have a prefs file and you set the game to borderless windowed, the ui breaks horribly. You have to quit the game and re-launch. Then the resolution selector is completely broken and you have to set another resolution and then quit and re-open the game again. After this, it never breaks again.

**Comment by AJ-Ferguson** [comment]
Fixed by ae37e50bcceb760311668b0571b6a9c5a09d6912
