### ISSUE TITLE
[BUG] spawnStupidMarble serverCmd not protected

### ISSUE THREAD

**Issue by maxymax13** [MBU-Team/OpenMBU#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Beta 1.16

### OS

Windows 10

### Description

We were playing the game and noticed that the spawnStupidMarble command has no kind of check for admin/host, so any player can spam `commandToServer('spawnStupidMarble',1);` as many times as they want until the host crashes.
![image](https://github.com/MBU-Team/OpenMBU/assets/38844529/4097a8f4-74a7-4c77-a8fa-9970b007ded0)

### Steps to reproduce

1. Join a multiplayer game
2. `commandToServer('spawnStupidMarble',1);`

### Expected Behavior

Only the host should be able to run this command

### Actual Behavior

Anyone can run this command

**Comment by neolightning** [comment]
This should be fixed in the next release.
