### ISSUE TITLE
[REQUEST] PS3 Port - Is it Possible?

### ISSUE THREAD

**Issue by darkralts** [MBU-Team/OpenMBU#186]
[//]: # (List and describe your features here:)

**Comment by neolightning** [comment]
Technically yes, however have fun gaining access to the PS3 development kits in order to make this happen.

**Comment by darkralts** [comment]
hahahaha, if i ever manage to will do. 👌 thank you for the whole-hearted
reply

**Comment by MysticAx0lotl** [comment]
> Technically yes, however have fun gaining access to the PS3 development kits in order to make this happen.

There are open source PS3 SDKs

**Comment by darkralts** [comment]
thats what i was thinking, theres gotta be one thanks

On Wednesday, 8 November 2023, MysticAx0lotl ***@***.***>
wrote:
> Technically yes, however have fun gaining access to the PS3 development
kits in order to make this happen.
>
> There are open source PS3 SDKs
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/KhnJAcvZOSs4AW31YFmnszcIQVhmplK-8q33v9uo_c8g4YuToRUMOoXI4RywG2dTLPhFcArOORt1UvgkzTOnLXN-8eoTJ7V8zELmtadAaHURyYQclibY6i-gSCQOu4mHaDt6c2asPuw6XblDVMfjFr-zBkAMg3pyyjtsFcs3g27g8kvPV7A-i8KKv37J9l11OBAop-Fexk_fG7dktJHNhp4cFUGgXrIFG-hbWBDbwGbefGrzYw=s0-d-e1-ft#https://github.com/notifications/beacon/AD43UGY5POXTXFPMP6A2QZTYDRB5HA5CNFSM6AAAAAA634OMFCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTLPD6VW.gif>Message
ID: ***@***.***>
