### ISSUE TITLE
[BUG] Discord RPC No Longer Works 

### ISSUE THREAD

**Issue by neolightning** [MBU-Team/OpenMBU#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Other (please specify elsewhere)

### OS

Windows 11

### Description

Trying to invite players via discord no longer works. 
![image](https://github.com/MBU-Team/OpenMBU/assets/6211989/8c105992-fd92-4b1d-8cd9-b2d9a1a3dc49)

Higuy Chat Fix Brand

### Steps to reproduce

Create MP Match, and try to invite a friend via Discord.

### Expected Behavior

Send Invite Card

### Actual Behavior

Gives DM Error like you are banned from chatting

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/MBU-Team/OpenMBU/commit/0328db69347f9a0bff5342242b34ff966fdd7e94
