### ISSUE TITLE
[BUG] Shaders Included With Custom Levels Can't Be Found When the Level's Folder is a .zip

### ISSUE THREAD

**Issue by TheGreatAutismo** [MBU-Team/OpenMBU#214]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

Beta 1.16

### OS

Windows 10

### Description

This is for Beta 1.17, not Beta 1.16. There was no Beta 1.17 option in the Version drop-down

https://discord.com/channels/265605947144142848/300452416455835649/1223668359518879805
For custom levels that use their own custom shaders for certain textures, if the level's files are zipped up rather than just being in a normal folder, the interiors which use textures which use those shaders do not appear.

### Log File

[console.log](https://github.com/MBU-Team/OpenMBU/files/14812850/console.log)

### Steps to reproduce

1. Download Multiplayer.zip v25.0
2. Load any level which uses a "4x4" texture (Collector's World and Fault Line are good examples, as they feature interiors both with and without these 4x4 textures)
3. ???
4. Deficit

### Expected Behavior

The respective interiors appear with the textures applied and the custom shaders with it.

### Actual Behavior

The interiors don't even appear in the level

### Reproduction frequency

100% of the time

### Additional Information

This only happens with shaders, but levels with custom textures only and no custom shaders (such as Sacred) work correctly.

**Comment by HumanGamer** [comment]
Fixed in bd96bd959162dafabc4b683f4b788c2c12964a0f
