### ISSUE TITLE
[Bug] When the Game is paused, other sound effects persist until menu interaction

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#58]

**Comment by HumanGamer** [comment]
I will have to confirm if this happens on console.

**Comment by CDAGaming** [comment]
One way to reproduce reliably is to have the marble roll then pause while still rolling, or to do an effect and pause at the same relative time

**Comment by CDAGaming** [comment]
Also can confirm this is still present in the 1.1 version
