### ISSUE TITLE
[Bug] Font distortion (Several texts using a fallback font of sorts)

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#62]
![image](https://user-images.githubusercontent.com/16328918/118572086-32552780-b745-11eb-823c-078ae7842510.png)
![image](https://user-images.githubusercontent.com/16328918/118572099-3719db80-b745-11eb-8415-06cc06eec246.png)

Some cases of the font distortion, but present in numerous other places.

**Comment by HumanGamer** [comment]
Oh I completely forgot about making an issue for this. As a temporary workaround, install the font I included in this repository. Something is up with the font caching and I don't know what. I haven't had time to look into it.
