### ISSUE TITLE
[Bug] Winning Beam rough in certain angles (Different camera angles make the beam look jagged)

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#63]
![image](https://user-images.githubusercontent.com/16328918/118572134-544eaa00-b745-11eb-83c7-c0a66500b241.png)

This is just one specific angle, but other angles produce the same/worse effect on the beam.

**Comment by HumanGamer** [comment]
Likely related to #34 or #36

**Comment by CDAGaming** [comment]
As #34 was closed, Ill be retesting this on the bewest release shortly.

**Comment by CDAGaming** [comment]
![2021-05-27 (4)](https://user-images.githubusercontent.com/16328918/119904306-c37b8980-bf0f-11eb-80b7-cb6ca4eae35f.png)
Still present in v1.3.1, issue will remain open

**Comment by HumanGamer** [comment]
I'm pretty sure it looked like that on Xbox 360. Will need to double check.

**Comment by MrTwatWaffle** [comment]
Just checked. it was like this on the 360

**Comment by HumanGamer** [comment]
Ah, ok. Closing in that case.
