### ISSUE TITLE
[Issue/Request] Winning Beam should be visible through glass, like the skybox is able to

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#64]
Unsure if intended, marked as bug just in case.

![image](https://user-images.githubusercontent.com/16328918/118572169-72b4a580-b745-11eb-9e15-080efd666608.png)

**Comment by HumanGamer** [comment]
Related to #35

**Comment by HumanGamer** [comment]
Fixed in 81cb02e3adb92523af1a1c5b89b447d97f0513d0
