### ISSUE TITLE
[Bug] Graphical defect while marble is in Winning beam

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#65]
Forgot to nab a screenshot of this, but it seems to always occur (Only effects top half of the marble)

**Comment by HumanGamer** [comment]
Does this still happen in the latest version for you?

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/119198952-d5f94d00-ba4f-11eb-893c-6a1d22bb12ca.png)
Confirmed Fixed, closing as resolved!
