### ISSUE TITLE
[Bug] Blast effect has visible rectangular borders (Visible when used during OOB screen)

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#67]
![2021-05-21_14](https://user-images.githubusercontent.com/39096122/121444592-71962300-c955-11eb-8aca-55443e89e24e.png)

**Comment by HumanGamer** [comment]
Can you make a video of this? (Or at least a screenshot)

**Comment by CDAGaming** [comment]
I can try to, though the effect is so quick it's hard to notice. Only time it's really noticable is if you use your blast ability right during the out of bounds screen.

**Comment by HumanGamer** [comment]
@CDAGaming I added your screenshot.

**Comment by HumanGamer** [comment]
Can anyone confirm if this is still an issue as of #94 being fixed?

**Comment by neolightning** [comment]
After testing I have noticed that it doesn't seem to be a issue anymore. Closing this issue, if anyone see's this as of [6a51ed6](https://github.com/MBU-Team/OpenMBU/commit/6a51ed6f0ff233172936aed1fd32dd75c51c62b8), please let us know
