### ISSUE TITLE
[BUG] Ghost Beam On Multiplayer Gems

### ISSUE THREAD

**Issue by neolightning** [MBU-Team/OpenMBU#71]
Ghost Beam On Multiplayer Gems

Beam should be removed when gem is collected

**Comment by HumanGamer** [comment]
If anybody is able to reproduce this, please share what you did, and provide console.log

**Comment by thearst3rd** [comment]
Closing since nobody has reproduced this since the hifi fixes were merged. If it happens again, we'll reopen.
