### ISSUE TITLE
[BUG] Controller inputs are stored when restarting from pause

### ISSUE THREAD

**Issue by DeathP** [MBU-Team/OpenMBU#74]
[//]: # (Describe what's going wrong:)
360 controller. When holding the left stick in some direction, pause, release the stick, restart. The marble spins the same as it would at the pre-pause stick position. Holding and releasing RT through a restart in the same manner makes it so powerups are activated on pick-up, until RT is pressed again. Jump seems to work fine and does not stay in a jumping state through pause.

[//]: # (Describe what should happen:)
Honestly unsure if it existed on 360, but I'm leaning toward no. I believe everything aside from marble orientation should reset to neutral/zero.

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by DeathP** [comment]
I think this solution caused inputs to disappear after _resuming_ from pause as well. Holding a direction before and after pause results in no acceleration unless you release to change direction.

**Comment by HumanGamer** [comment]
Yea, that's how I fixed it. I'm not really sure how to fix it otherwise...
