### ISSUE TITLE
[BUG] Camera does not consider Glass as a collidable object

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#79]
![image](https://user-images.githubusercontent.com/16328918/119199114-22448d00-ba50-11eb-9c66-c1d2a5d2a837.png)

**Comment by CDAGaming** [comment]
The specific way to reproduce this is to position the camera so it is outside the glass, then move the marble left to where the marble's camera logically cant move outside the glass, but the camera is still on the other end

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/119199352-823b3380-ba50-11eb-825a-1b4a8339dbdb.png)

**Comment by HumanGamer** [comment]
This is how it works in MBO. It's not worth fixing right now.
