### ISSUE TITLE
[BUG] It is possible to pause-buffer the marble intro

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#80]
It is possible to pause the game when you spawn in and have the timeUntilDrop continue ticking down, resulting in a normal animation for the entry area but an early drop

**Comment by CDAGaming** [comment]
![Uploading 2021-05-21 (18).png…]()

**Comment by CDAGaming** [comment]
![2021-05-21 (18)](https://user-images.githubusercontent.com/16328918/119200729-1d350d00-ba53-11eb-9d26-07805fdcc12c.png)

**Comment by neolightning** [comment]
This happens on Xbox too, its known as the Early Start glitch.

**Comment by CDAGaming** [comment]
Ah neat, I'll close as intended in that case
