### ISSUE TITLE
[BUG] Collecting a TT and then restarting the level will cause the TT sound to continue playing until you restart the level again

### ISSUE THREAD

**Issue by MrTwatWaffle** [MBU-Team/OpenMBU#88]
Collecting a TT and then restarting the level will cause the TT sound to continue playing intel you restart the level again

**Comment by HumanGamer** [comment]
@MrTwatWaffle I can't reproduce this on Beta 1.6. Does this still happen?

**Comment by HumanGamer** [comment]
This seems to have been fixed at some point, and I have no idea why. Closing.
