### ISSUE TITLE
[REQUEST] Allow custom usernames for multiplayer

### ISSUE THREAD

**Issue by thearst3rd** [MBU-Team/OpenMBU#96]
Probably relates to issues like #6.

I found the prefs.cs file and changed `$Pref::Server::Name` to be what I want my online username to be, rather than just my Windows username. But it got reverted back when I launched the game.

Relevant code snippet: https://github.com/MBU-Team/OpenMBU/blob/87b8a42ba78efb67a978c731cb0817799400033d/engine/source/xblive/xbliveFunctions.cpp#L90-L101

There are multiple instances of this function being called, some are `$Player::Name = XBLiveGetUserName();`, and I did find one `$pref::Server::Name = XBLiveGetUserName();` in createGameGui.gui: https://github.com/MBU-Team/OpenMBU/blob/87b8a42ba78efb67a978c731cb0817799400033d/game/marble/client/ui/createGameGui.gui#L326

I'm not too familiar with how the engine works or exactly which one the "culprit" is, but it would be nice for it to not override the name if there is already one there.

**Comment by neolightning** [comment]
This will be added once we have a login system for the game. The current method is a temporary way of making sure everyone is not called "Alex"

**Comment by RandomityGuy** [comment]
Implemented in https://github.com/MBU-Team/OpenMBU/commit/065dfdc8f6a714ae8547ca10f2252700d2e21c48
